from brkga_mp_ipr.types import BaseChromosome


class VRPDecoder:
    """
    Decoder for the Capacitated Vehicle Routing Problem (CVRP).

    A chromosome encodes a customer visitation order using random keys.
    The decoder splits the sequence into feasible routes according to
    vehicle capacity constraints and evaluates the corresponding solution.

    Parameters
    ----------
    K : int
        Number of vehicles.

    N : int
        Number of nodes, including the depot.

    Q : float
        Vehicle capacity.

    d : np.ndarray
        Demand vector.

    D : np.ndarray
        Distance matrix.
    """
    def __init__(self, K, N, Q, d, D):
        num_nodes = N
        self.num_vehicles = K
        self.vehicle_capacity = Q
        self.demands = d
        self.distance_matrix = D
        self.PENALTY = 1e5

        if any(self.demands[i] > self.vehicle_capacity
                for i in range(1, num_nodes)):
            raise ValueError(
                "Infeasible CVRP instance:"
                "customer demand exceeds vehicle capacity."
            )

    def two_swap(self, routes: list[list[int]]) -> list[list[int]]:
        improved = True
        loads = [sum(self.demands[c] for c in r) for r in routes]

        while improved:
            improved = False
            for i in range(len(routes)):
                for j in range(i + 1, len(routes)):
                    for id_a in range(len(routes[i])):
                        for id_b in range(len(routes[j])):
                            u = routes[i][id_a]
                            v = routes[j][id_b]

                            load_a = (
                                loads[i]
                                - self.demands[u]
                                + self.demands[v]
                            )
                            load_b = (
                                loads[j]
                                - self.demands[v]
                                + self.demands[u]
                            )

                            if (
                                load_a > self.vehicle_capacity
                                or load_b > self.vehicle_capacity
                            ):
                                continue

                            before = (
                                self.cost_per_route(routes[i])
                                + self.cost_per_route(routes[j])
                            )

                            new_i = routes[i][:]
                            new_j = routes[j][:]
                            new_i[id_a] = v
                            new_j[id_b] = u

                            after = (
                                self.cost_per_route(new_i)
                                + self.cost_per_route(new_j)
                            )

                            if after < before - 1e-6:
                                routes[i] = new_i
                                routes[j] = new_j
                                loads[i] = load_a
                                loads[j] = load_b
                                improved = True

        return routes

    def decode(self, chromosome: BaseChromosome, rewrite: bool) -> float:
        """
        Decode a BRKGA chromosome and return its objective value.
        """

        routes = self.get_routes(chromosome)

        if len(routes) > self.num_vehicles:
            excess = len(routes) - self.num_vehicles
            return self.total_cost(routes) + self.PENALTY * excess

        return self.total_cost(routes)

    def get_routes(self, chromosome: BaseChromosome) -> list[list[int]]:
        """
        Compute the routes from chromosome generated by BRKGA.
        """

        order = sorted(
            range(1, len(chromosome) + 1),
            key=lambda i: chromosome[i - 1]
        )

        routes = []
        current_route = []
        current_load = 0.0

        for point in order:
            if current_load + self.demands[point] > self.vehicle_capacity:
                if current_route:
                    routes.append(current_route)
                current_route = [point]
                current_load = self.demands[point]

            else:
                current_route.append(point)
                current_load += self.demands[point]

        if current_route:
            routes.append(current_route)

        return routes

    def cost_per_route(self, route: list[int]) -> float:
        """
        Compute the travel cost per route.
        """

        if not route:
            return 0.0

        route = [0] + route + [0]
        cost = sum(
            self.distance_matrix[i][j]
            for i, j in zip(route[:-1], route[1:])
        )
        return cost

    def total_cost(self, routes: list[list[int]]) -> float:
        """
        Compute the total travel cost of a set of CVRP routes.
        """
        cost = sum(self.cost_per_route(r) for r in routes)

        if len(routes) > self.num_vehicles:
            return cost + self.PENALTY

        return cost
